#property strict
#property description "Wise Men wave-based strategy"
#property version   "1.00"
#property copyright "Generated by ChatGPT"

#include <Trade/Trade.mqh>

input int    INTERVAL=60;        // Seconds between data sampling
input int    BACKTIME=20;        // Number of intervals to define a wave
input double PERCENT=0.5;        // Percent relation for Point3/Point6
input int    WAVECHECK=50;       // Maximum intervals since last wave
input double STOPATR1=1.5;       // ATR multiple for Wise Man 1
input double STOPATR2=1.5;       // ATR multiple for Wise Man 2
input double STOPATR3=1.5;       // ATR multiple for Wise Man 3
input double RR1=2.0;            // Risk reward for Wise Man 1
input double RR2=3.0;            // Risk reward for Wise Man 2
input double RR3=4.0;            // Risk reward for Wise Man 3
input double RiskPercent=1.0;    // Percent equity risk per trade
input int    HALF=20;            // Interval steps for stop management
input int    TCLOSE=200;         // Maximum intervals to keep trade

input double Wt=40.0;            // Weight for trade density
input double Wp=40.0;            // Weight for monthly profit
input double Wd=20.0;            // Weight for drawdown

struct DataPoint
{
   datetime time;
   double   price;
};

struct TradeInfo
{
   ulong    ticket;
   datetime open_time;
   double   entry;
   double   initial_sl;
   double   risk;
   int      step; // 0..3 for stop adjustments
};

CTrade trade;

//--- storage for price points
DataPoint  points[];
int        last_wave_index=-1;
datetime   start_time;      // start and end time for tester stats
datetime   end_time;

double     start_equity;
int        total_trades=0;

//--- wave points
struct Wave
{
   double p1,p2,p3,p4,p5,p6;
   bool   up;  // true for up-wave
   datetime time4;
   bool   valid;
};
Wave current_wave;

TradeInfo trades[10]; // allow up to 10 concurrent trades

//+------------------------------------------------------------------+
//| Expert initialization                                            |
//+------------------------------------------------------------------+
int OnInit()
{
   ArrayInitialize(trades,0);
   ArrayResize(points,0);
   EventSetTimer(INTERVAL);
   start_time=TimeCurrent();
   start_equity=AccountInfoDouble(ACCOUNT_EQUITY);
   current_wave.valid=false;
   return(INIT_SUCCEEDED);
}
//+------------------------------------------------------------------+
//| Expert deinitialization                                          |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   EventKillTimer();
   end_time=TimeCurrent();
}

//+------------------------------------------------------------------+
//| Helper: store price                                              |
//+------------------------------------------------------------------+
void AddPoint()
{
   DataPoint dp;
   dp.time=TimeCurrent();
   dp.price=SymbolInfoDouble(_Symbol,SYMBOL_LAST);
   int size=ArraySize(points);
   ArrayResize(points,size+1);
   points[size]=dp;
}

//+------------------------------------------------------------------+
//| Helper: detect wave                                              |
//+------------------------------------------------------------------+
bool DetectWave()
{
   int size=ArraySize(points);
   if(size<BACKTIME)
      return(false);

   int start=size-BACKTIME;
   double p1=points[start].price;
   double p4=points[size-1].price;
   //--- check direction
   bool up=true;
   double min=p1,max=p4;
   for(int i=start;i<size;i++)
   {
      double pr=points[i].price;
      if(pr<min) min=pr;
      if(pr>max) max=pr;
   }
   if(p1!=min || p4!=max)
   {
      // try down wave
      up=false;
      if(p1!=max || p4!=min)
         return(false);
   }

   // locate Point2
   int idx2=start+1;
   double p2=points[idx2].price;
   for(int i=start+1;i<size-1;i++)
   {
      if( ( up && points[i].price>p2) || (!up && points[i].price<p2) )
      {
         p2=points[i].price;
         idx2=i;
      }
   }
   // locate Point3 after Point2
   int idx3=idx2+1;
   if(idx3>=size-1) return(false);
   double p3=points[idx3].price;
   for(int i=idx2+1;i<size-1;i++)
   {
      if( ( up && points[i].price<p3) || (!up && points[i].price>p3) )
      {
         p3=points[i].price;
         idx3=i;
      }
   }
   double expected=p1 + PERCENT*(p2-p1);
   if(MathAbs(p3-expected) > SymbolInfoDouble(_Symbol,SYMBOL_POINT)*10)
      return(false);

   current_wave.p1=p1; current_wave.p2=p2; current_wave.p3=p3; current_wave.p4=p4;
   current_wave.p5=p4; current_wave.p6=p3 + PERCENT*(current_wave.p5 - p3);
   current_wave.up=up;
   current_wave.time4=points[size-1].time;
   current_wave.valid=true;
   last_wave_index=size-1;
   return(true);
}

//+------------------------------------------------------------------+
//| Calculate ATR                                                     |
//+------------------------------------------------------------------+
double CurrentATR()
{
   return(iATR(_Symbol,_Period,14,0));
}

//+------------------------------------------------------------------+
//| Position sizing                                                   |
//+------------------------------------------------------------------+
double CalcLot(double stop_price,double entry_price)
{
   double risk=RiskPercent/100.0*AccountInfoDouble(ACCOUNT_EQUITY);
   double tick_value=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE);
   double tick_size=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);
   double stop_distance=MathAbs(entry_price-stop_price);
   double lot=risk/((stop_distance/tick_size)*tick_value);
   double min_lot=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   double lot_step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   lot=NormalizeDouble(MathMax(min_lot,lot),2);
   lot=MathFloor(lot/lot_step)*lot_step;
   return(lot);
}

//+------------------------------------------------------------------+
//| Trade management                                                  |
//+------------------------------------------------------------------+
void ManageTrades()
{
   datetime now=TimeCurrent();
   for(int i=0;i<ArraySize(trades);i++)
   {
      if(trades[i].ticket==0) continue;
      CPositionInfo pos;
      if(!pos.SelectByTicket(trades[i].ticket))
      {
         trades[i].ticket=0;
         continue;
      }
      int passed=(int)((now-trades[i].open_time)/INTERVAL);
      double new_sl=trades[i].initial_sl;
      double dir=pos.PositionType()==POSITION_TYPE_BUY?1:-1;
      if(passed>=HALF && trades[i].step==0)
      {
         new_sl=trades[i].entry - dir*trades[i].risk/2.0;
         trades[i].step=1;
      }
      else if(passed>=2*HALF && trades[i].step==1)
      {
         new_sl=trades[i].entry - dir*trades[i].risk/4.0;
         trades[i].step=2;
      }
      else if(passed>=3*HALF && trades[i].step==2)
      {
         new_sl=trades[i].entry;
         trades[i].step=3;
      }
      if(trades[i].step>0)
         trade.PositionModify(trades[i].ticket,new_sl,0);
      if(passed>=TCLOSE)
      {
         trade.PositionClose(trades[i].ticket);
         trades[i].ticket=0;
      }
   }
}

//+------------------------------------------------------------------+
//| Open trade helper                                                 |
//+------------------------------------------------------------------+
void OpenTrade(double entry,double sl,double tp,bool buy)
{
   double lot=CalcLot(sl,entry);
   bool ok;
   if(buy)
      ok=trade.Buy(lot,_Symbol,entry,sl,tp);
   else
      ok=trade.Sell(lot,_Symbol,entry,sl,tp);
   if(ok)
   {
      ulong ticket=trade.ResultOrder();
      CPositionInfo pos;
      if(pos.SelectByTicket(ticket))
      {
         int idx=-1;
         for(int i=0;i<ArraySize(trades);i++) if(trades[i].ticket==0){idx=i;break;}
         if(idx!=-1)
         {
            trades[idx].ticket=pos.Ticket();
            trades[idx].open_time=TimeCurrent();
            trades[idx].entry=pos.PriceOpen();
            trades[idx].initial_sl=sl;
            trades[idx].risk=MathAbs(pos.PriceOpen()-sl);
            trades[idx].step=0;
            total_trades++;
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Timer event                                                       |
//+------------------------------------------------------------------+
void OnTimer()
{
   AddPoint();
   int size=ArraySize(points);
   if(current_wave.valid && size-last_wave_index>WAVECHECK)
      current_wave.valid=false;
   // detect wave if none
   if(!current_wave.valid)
      DetectWave();

   if(current_wave.valid)
   {
      double price=points[size-1].price;
      if( (current_wave.up && price>current_wave.p5) || (!current_wave.up && price<current_wave.p5) )
      {
         current_wave.p5=price;
         current_wave.p6=current_wave.p3 + PERCENT*(current_wave.p5-current_wave.p3);
      }

      bool buy=current_wave.up;
      // Wise Man 1
      if(!PositionSelect("WM1") && ((buy && price>=current_wave.p6) || (!buy && price<=current_wave.p6)))
      {
         double atr=CurrentATR();
         double sl=buy?current_wave.p3-atr*STOPATR1:current_wave.p3+atr*STOPATR1;
         double tp=buy?current_wave.p6+(current_wave.p6-sl)*RR1:current_wave.p6-(sl-current_wave.p6)*RR1;
         trade.SetExpertMagicNumber(1);
         trade.SetExpertComment("WM1");
         OpenTrade(current_wave.p6,sl,tp,buy);
      }
      // Wise Man 2
      if(PositionSelectByMagic(1))
      {
         CPositionInfo pos1;
         pos1.SelectByMagic(1);
         bool w2_opened=PositionSelect("WM2");
         if(!w2_opened)
         {
            if((buy && price>pos1.PriceOpen()) || (!buy && price<pos1.PriceOpen()))
            {
               double atr=CurrentATR();
               double entry=price;
               double sl=buy?current_wave.p3-atr*STOPATR2:current_wave.p3+atr*STOPATR2;
               double tp=buy?entry+(entry-sl)*RR2:entry-(sl-entry)*RR2;
               trade.SetExpertMagicNumber(2);
               trade.SetExpertComment("WM2");
               OpenTrade(entry,sl,tp,buy);
            }
         }
      }
      // Wise Man 3
      bool w3_opened=PositionSelect("WM3");
      if(!w3_opened && ((buy && price>current_wave.p5) || (!buy && price<current_wave.p5)))
      {
         double atr=CurrentATR();
         double entry=price;
         double sl=buy?current_wave.p3-atr*STOPATR3:current_wave.p3+atr*STOPATR3;
         double tp=buy?entry+(entry-sl)*RR3:entry-(sl-entry)*RR3;
         trade.SetExpertMagicNumber(3);
         trade.SetExpertComment("WM3");
         OpenTrade(entry,sl,tp,buy);
      }
   }
   ManageTrades();
}

//+------------------------------------------------------------------+
//| Tester optimization function                                      |
//+------------------------------------------------------------------+
double OnTester()
{
   double total_profit=TesterStatistics(STAT_PROFIT);
   double dd=TesterStatistics(STAT_EQUITY_DDREL_PERCENT)/100.0;

   double months=(end_time-start_time)/(30.4375*86400.0);
   if(months<=0) months=1.0;
   double bars=(end_time-start_time)/(PeriodSeconds(_Period));
   double T=(bars>0)?((double)total_trades/bars):0;
   double P=(start_equity>0)?((total_profit/start_equity)/months):0;

   double y=T*Wt + P*Wp - dd*Wd;
   return(y*100.0);
}

//+------------------------------------------------------------------+
//| Utility to select by comment                                     |
//+------------------------------------------------------------------+
bool PositionSelect(const string comment)
{
   int total=PositionsTotal();
   for(int i=0;i<total;i++)
   {
      ulong ticket=PositionGetTicket(i);
      string comm=PositionGetString(POSITION_COMMENT);
      if(comm==comment) {return(true);}
   }
   return(false);
}

bool PositionSelectByMagic(uint magic)
{
   int total=PositionsTotal();
   for(int i=0;i<total;i++)
   {
      ulong ticket=PositionGetTicket(i);
      uint mg=(uint)PositionGetInteger(POSITION_MAGIC);
      if(mg==magic) {return(true);}
   }
   return(false);
}

//+------------------------------------------------------------------+
